api_version = "2024-10"

[[extensions]]
uid = "fb383981-6114-c7fc-fe5f-8ea321524cf0b1448f57"
type = "theme_app_extension"
name = "CRO Optimizer"
handle = "cro-optimizer"

[extensions.capabilities]
assets = true
blocks = true
snippets = false
